### PR TITLE
Register the layout renderer

### PR DESCRIPTION
**Pull request by petemounce**
... but when I do this, tests start to fail

### CODE REVIEW

**Comment by petemounce** [comment]
@304NotModified
Here's the nullref shot
The `propertyInfo` variable is null. `value` is "c", property is "c". `path` is [3] { "a", "b", "c" }.

**Comment by petemounce** [comment]
Here is the invalidoperationexception

`path` here is an empty array, `key` is an empty string.

**Comment by 304NotModified** [comment]
Sounds like a bug. Which can be fixed easily.  :)

**Comment by 304NotModified** [comment]
BugS

**Pull request closed without merging**
